# Generated by Django 5.1.7 on 2025-04-11 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digitalcontent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalcontent",
            name="created_by",
            field=models.CharField(default="admin", max_length=100),
        ),
        migrations.AddField(
            model_name="digitalcontent",
            name="image",
            field=models.ImageField(
                default="profile_images/membership_sample_page.jpg",
                upload_to="digitalcontent/images/",
            ),
        ),
        migrations.AlterField(
            model_name="digitalcontent",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="RegisteredContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digitalcontent.digitalcontent",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="RegisteredResource",
        ),
    ]
