# Generated by Django 5.1.6 on 2025-02-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("interests", models.JSONField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("user", "User"),
                            ("guest", "Guest"),
                        ],
                        default="user",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
