# Generated by Django 5.1.6 on 2025-03-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_remove_users_status_users_groups_users_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("guest", "Guest"),
                    ("community", "Community Holder"),
                    ("key", "Key Access Holder"),
                    ("workspace", "Create Workspace Holder"),
                ],
                default="guest",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
