# Generated by Django 5.1.7 on 2025-04-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_users_account_type_users_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("guest", "Guest"),
                    ("rejected", "Rejected"),
                    ("community holder", "Community Holder"),
                    ("key access holder", "Key Access Holder"),
                    ("create workspace holder", "Create Workspace Holder"),
                ],
                default="guest",
                max_length=50,
            ),
        ),
    ]
